//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaffaForWPF.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ja_JP() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JaffaForWPF.Resources.Resources_ja-JP", typeof(Resources_ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JAFFA_END {
            get {
                return ResourceManager.GetString("JAFFA_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JAFFA_START {
            get {
                return ResourceManager.GetString("JAFFA_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jaffaフレームワーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JAFFA_TITLE {
            get {
                return ResourceManager.GetString("JAFFA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JAFFA_VERSION {
            get {
                return ResourceManager.GetString("JAFFA_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ出力中に例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOGGING_EXCEPTION {
            get {
                return ResourceManager.GetString("LOGGING_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未サポートです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jaffaフレームワークの現在時刻が変更されました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIME_CHANGE {
            get {
                return ResourceManager.GetString("TIME_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIME_FORMAT {
            get {
                return ResourceManager.GetString("TIME_FORMAT", resourceCulture);
            }
        }
    }
}
